#!/bin/sh

###############################################################################
# Configuration
###############################################################################

if [ $# -ne 1 ]; then
   echo "usage: $0 <file>" 1>&2
   exit 1
fi

FILE=$1

TMP=`mktemp`
trap "rm -f $TMP" EXIT

cat "$FILE" > $TMP

###############################################################################
# Main
###############################################################################

# remove duplicated blank lines
# and remove trailing blank lines at the end of file
cat $TMP \
| perl -ane '$n=(@F==0) ? $n+1 : 0; print if $n<=1' \
| sed -e :a -e '/^[ \t]*\n*$/{$d;N;ba' -e '}' \
> "$FILE"
